/**
 * Shared constants for K10 Media Broadcaster Dashboard.
 * Extracted from config.js — all `const` declarations.
 */

import type { Settings, GameFeatures, CarAdjustability } from './types'

export const SIMHUB_URL = 'http://localhost:8889/k10mediabroadcaster/'
export const POLL_MS = 33 // ~30fps
export const CYCLE_INTERVAL_FRAMES = Math.round(10000 / POLL_MS) // 10s

// All properties we need, batched into a single request
export const PROP_KEYS: string[] = [
  'DataCorePlugin.GameRunning',
  'K10MediaBroadcaster.Plugin.GameId',
  'DataCorePlugin.GameData.Gear',
  'DataCorePlugin.GameData.Rpms',
  'DataCorePlugin.GameData.CarSettings_MaxRPM',
  'DataCorePlugin.GameData.SpeedMph',
  'DataCorePlugin.GameData.Throttle',
  'DataCorePlugin.GameData.Brake',
  'DataCorePlugin.GameData.Clutch',
  'DataCorePlugin.GameData.Fuel',
  'DataCorePlugin.GameData.MaxFuel',
  'DataCorePlugin.Computed.Fuel_LitersPerLap',
  'DataCorePlugin.GameData.RemainingLaps',
  'DataCorePlugin.GameData.TyreTempFrontLeft',
  'DataCorePlugin.GameData.TyreTempFrontRight',
  'DataCorePlugin.GameData.TyreTempRearLeft',
  'DataCorePlugin.GameData.TyreTempRearRight',
  'DataCorePlugin.GameData.TyreWearFrontLeft',
  'DataCorePlugin.GameData.TyreWearFrontRight',
  'DataCorePlugin.GameData.TyreWearRearLeft',
  'DataCorePlugin.GameData.TyreWearRearRight',
  'DataCorePlugin.GameRawData.Telemetry.dcBrakeBias',
  'DataCorePlugin.GameRawData.Telemetry.dcTractionControl',
  'DataCorePlugin.GameRawData.Telemetry.dcABS',
  'DataCorePlugin.GameRawData.Telemetry.dcAntiRollFront',
  'DataCorePlugin.GameRawData.Telemetry.dcAntiRollRear',
  'DataCorePlugin.GameData.Position',
  'DataCorePlugin.GameData.CurrentLap',
  'DataCorePlugin.GameData.BestLapTime',
  'DataCorePlugin.GameData.CarModel',
  'IRacingExtraProperties.iRacing_DriverInfo_IRating',
  'IRacingExtraProperties.iRacing_DriverInfo_SafetyRating',
  'IRacingExtraProperties.iRacing_Opponent_Ahead_Gap',
  'IRacingExtraProperties.iRacing_Opponent_Behind_Gap',
  'IRacingExtraProperties.iRacing_Opponent_Ahead_Name',
  'IRacingExtraProperties.iRacing_Opponent_Behind_Name',
  'IRacingExtraProperties.iRacing_Opponent_Ahead_IRating',
  'IRacingExtraProperties.iRacing_Opponent_Behind_IRating',
  'DataCorePlugin.GameRawData.Telemetry.FrameRate',
  'DataCorePlugin.GameRawData.Telemetry.SteeringWheelAngle',
  'DataCorePlugin.GameData.SessionTimeSpan',
  'DataCorePlugin.GameData.CurrentLapTime',
  'DataCorePlugin.GameData.LastLapTime',
  'DataCorePlugin.GameData.RemainingTime',
  'DataCorePlugin.GameData.TotalLaps',
  'K10MediaBroadcaster.Plugin.CommentaryVisible',
  'K10MediaBroadcaster.Plugin.CommentaryText',
  'K10MediaBroadcaster.Plugin.CommentaryTopicTitle',
  'K10MediaBroadcaster.Plugin.CommentaryTopicId',
  'K10MediaBroadcaster.Plugin.CommentaryCategory',
  'K10MediaBroadcaster.Plugin.CommentarySentimentColor',
  'K10MediaBroadcaster.Plugin.CommentarySeverity',
  'K10MediaBroadcaster.Plugin.SessionTypeName',
  'K10MediaBroadcaster.Plugin.DemoMode',
  'K10MediaBroadcaster.Plugin.Demo.Gear',
  'K10MediaBroadcaster.Plugin.Demo.Rpm',
  'K10MediaBroadcaster.Plugin.Demo.MaxRpm',
  'K10MediaBroadcaster.Plugin.Demo.SpeedMph',
  'K10MediaBroadcaster.Plugin.Demo.Throttle',
  'K10MediaBroadcaster.Plugin.Demo.Brake',
  'K10MediaBroadcaster.Plugin.Demo.Clutch',
  'K10MediaBroadcaster.Plugin.Demo.Fuel',
  'K10MediaBroadcaster.Plugin.Demo.MaxFuel',
  'K10MediaBroadcaster.Plugin.Demo.FuelPerLap',
  'K10MediaBroadcaster.Plugin.Demo.RemainingLaps',
  'K10MediaBroadcaster.Plugin.Demo.TyreTempFL',
  'K10MediaBroadcaster.Plugin.Demo.TyreTempFR',
  'K10MediaBroadcaster.Plugin.Demo.TyreTempRL',
  'K10MediaBroadcaster.Plugin.Demo.TyreTempRR',
  'K10MediaBroadcaster.Plugin.Demo.TyreWearFL',
  'K10MediaBroadcaster.Plugin.Demo.TyreWearFR',
  'K10MediaBroadcaster.Plugin.Demo.TyreWearRL',
  'K10MediaBroadcaster.Plugin.Demo.TyreWearRR',
  'K10MediaBroadcaster.Plugin.Demo.BrakeBias',
  'K10MediaBroadcaster.Plugin.Demo.TC',
  'K10MediaBroadcaster.Plugin.Demo.ABS',
  'K10MediaBroadcaster.Plugin.Demo.SessionTypeName',
  'K10MediaBroadcaster.Plugin.Demo.Position',
  'K10MediaBroadcaster.Plugin.Demo.CurrentLap',
  'K10MediaBroadcaster.Plugin.Demo.BestLapTime',
  'K10MediaBroadcaster.Plugin.Demo.CarModel',
  'K10MediaBroadcaster.Plugin.Demo.SessionTime',
  'K10MediaBroadcaster.Plugin.Demo.CurrentLapTime',
  'K10MediaBroadcaster.Plugin.Demo.LastLapTime',
  'K10MediaBroadcaster.Plugin.Demo.RemainingTime',
  'K10MediaBroadcaster.Plugin.Demo.TotalLaps',
  'K10MediaBroadcaster.Plugin.Demo.IRating',
  'K10MediaBroadcaster.Plugin.Demo.SafetyRating',
  'K10MediaBroadcaster.Plugin.Demo.GapAhead',
  'K10MediaBroadcaster.Plugin.Demo.GapBehind',
  'K10MediaBroadcaster.Plugin.Demo.DriverAhead',
  'K10MediaBroadcaster.Plugin.Demo.DriverBehind',
  'K10MediaBroadcaster.Plugin.Demo.IRAhead',
  'K10MediaBroadcaster.Plugin.Demo.IRBehind',
  'K10MediaBroadcaster.Plugin.DS.LatG',
  'K10MediaBroadcaster.Plugin.DS.LongG',
  'K10MediaBroadcaster.Plugin.DS.YawRate',
  'K10MediaBroadcaster.Plugin.DS.SteerTorque',
  'K10MediaBroadcaster.Plugin.DS.TrackTemp',
  'K10MediaBroadcaster.Plugin.DS.IncidentCount',
  'K10MediaBroadcaster.Plugin.DS.AbsActive',
  'K10MediaBroadcaster.Plugin.DS.TcActive',
  'K10MediaBroadcaster.Plugin.DS.TrackPct',
  'K10MediaBroadcaster.Plugin.DS.LapDelta',
  'K10MediaBroadcaster.Plugin.DS.CompletedLaps',
  'K10MediaBroadcaster.Plugin.DS.IsInPitLane',
  'K10MediaBroadcaster.Plugin.DS.SpeedKmh',
  'K10MediaBroadcaster.Plugin.DS.PitLimiterOn',
  'K10MediaBroadcaster.Plugin.DS.PitSpeedLimitKmh',
  'K10MediaBroadcaster.Plugin.DS.ThrottleNorm',
  'K10MediaBroadcaster.Plugin.DS.BrakeNorm',
  'K10MediaBroadcaster.Plugin.DS.ClutchNorm',
  'K10MediaBroadcaster.Plugin.DS.RpmRatio',
  'K10MediaBroadcaster.Plugin.DS.FuelPct',
  'K10MediaBroadcaster.Plugin.DS.FuelLapsRemaining',
  'K10MediaBroadcaster.Plugin.DS.SpeedMph',
  'K10MediaBroadcaster.Plugin.DS.PitSpeedLimitMph',
  'K10MediaBroadcaster.Plugin.DS.IsPitSpeeding',
  'K10MediaBroadcaster.Plugin.DS.IsNonRaceSession',
  'K10MediaBroadcaster.Plugin.DS.IsTimedRace',
  'K10MediaBroadcaster.Plugin.DS.IsEndOfRace',
  'K10MediaBroadcaster.Plugin.DS.PositionDelta',
  'K10MediaBroadcaster.Plugin.DS.StartPosition',
  'K10MediaBroadcaster.Plugin.DS.RemainingTimeFormatted',
  'K10MediaBroadcaster.Plugin.DS.SpeedDisplay',
  'K10MediaBroadcaster.Plugin.DS.RpmDisplay',
  'K10MediaBroadcaster.Plugin.DS.FuelFormatted',
  'K10MediaBroadcaster.Plugin.DS.FuelPerLapFormatted',
  'K10MediaBroadcaster.Plugin.DS.PitSuggestion',
  'K10MediaBroadcaster.Plugin.DS.BBNorm',
  'K10MediaBroadcaster.Plugin.DS.TCNorm',
  'K10MediaBroadcaster.Plugin.DS.ABSNorm',
  'K10MediaBroadcaster.Plugin.DS.PositionDeltaDisplay',
  'K10MediaBroadcaster.Plugin.DS.LapDeltaDisplay',
  'K10MediaBroadcaster.Plugin.DS.SafetyRatingDisplay',
  'K10MediaBroadcaster.Plugin.DS.GapAheadFormatted',
  'K10MediaBroadcaster.Plugin.DS.GapBehindFormatted',
  'K10MediaBroadcaster.Plugin.Demo.DS.LatG',
  'K10MediaBroadcaster.Plugin.Demo.DS.LongG',
  'K10MediaBroadcaster.Plugin.Demo.DS.YawRate',
  'K10MediaBroadcaster.Plugin.Demo.DS.SteerTorque',
  'K10MediaBroadcaster.Plugin.Demo.DS.TrackTemp',
  'K10MediaBroadcaster.Plugin.Demo.DS.IncidentCount',
  'K10MediaBroadcaster.Plugin.Demo.DS.AbsActive',
  'K10MediaBroadcaster.Plugin.Demo.DS.TcActive',
  'K10MediaBroadcaster.Plugin.Demo.DS.LapDelta',
  'K10MediaBroadcaster.Plugin.Demo.DS.IsInPitLane',
  'K10MediaBroadcaster.Plugin.Demo.DS.SpeedKmh',
  'K10MediaBroadcaster.Plugin.Demo.DS.PitLimiterOn',
  'K10MediaBroadcaster.Plugin.Demo.DS.PitSpeedLimitKmh',
  'K10MediaBroadcaster.Plugin.Demo.DS.ThrottleNorm',
  'K10MediaBroadcaster.Plugin.Demo.DS.BrakeNorm',
  'K10MediaBroadcaster.Plugin.Demo.DS.ClutchNorm',
  'K10MediaBroadcaster.Plugin.Demo.DS.RpmRatio',
  'K10MediaBroadcaster.Plugin.Demo.DS.FuelPct',
  'K10MediaBroadcaster.Plugin.Demo.DS.FuelLapsRemaining',
  'K10MediaBroadcaster.Plugin.Demo.DS.SpeedMph',
  'K10MediaBroadcaster.Plugin.Demo.DS.PitSpeedLimitMph',
  'K10MediaBroadcaster.Plugin.Demo.DS.IsPitSpeeding',
  'K10MediaBroadcaster.Plugin.Demo.DS.IsNonRaceSession',
  'K10MediaBroadcaster.Plugin.Demo.DS.IsTimedRace',
  'K10MediaBroadcaster.Plugin.Demo.DS.IsEndOfRace',
  'K10MediaBroadcaster.Plugin.Demo.DS.PositionDelta',
  'K10MediaBroadcaster.Plugin.Demo.DS.StartPosition',
  'K10MediaBroadcaster.Plugin.Demo.DS.RemainingTimeFormatted',
  'K10MediaBroadcaster.Plugin.Demo.DS.SpeedDisplay',
  'K10MediaBroadcaster.Plugin.Demo.DS.RpmDisplay',
  'K10MediaBroadcaster.Plugin.Demo.DS.FuelFormatted',
  'K10MediaBroadcaster.Plugin.Demo.DS.FuelPerLapFormatted',
  'K10MediaBroadcaster.Plugin.Demo.DS.PitSuggestion',
  'K10MediaBroadcaster.Plugin.Demo.DS.BBNorm',
  'K10MediaBroadcaster.Plugin.Demo.DS.TCNorm',
  'K10MediaBroadcaster.Plugin.Demo.DS.ABSNorm',
  'K10MediaBroadcaster.Plugin.Demo.DS.PositionDeltaDisplay',
  'K10MediaBroadcaster.Plugin.Demo.DS.LapDeltaDisplay',
  'K10MediaBroadcaster.Plugin.Demo.DS.SafetyRatingDisplay',
  'K10MediaBroadcaster.Plugin.Demo.DS.GapAheadFormatted',
  'K10MediaBroadcaster.Plugin.Demo.DS.GapBehindFormatted',
  'K10MediaBroadcaster.Plugin.TrackMap.Ready',
  'K10MediaBroadcaster.Plugin.TrackMap.SvgPath',
  'K10MediaBroadcaster.Plugin.TrackMap.PlayerX',
  'K10MediaBroadcaster.Plugin.TrackMap.PlayerY',
  'K10MediaBroadcaster.Plugin.TrackMap.Opponents',
  'K10MediaBroadcaster.Plugin.Leaderboard',
  'K10MediaBroadcaster.Plugin.DriverFirstName',
  'K10MediaBroadcaster.Plugin.DriverLastName',
  'currentFlagState',
  'K10MediaBroadcaster.Plugin.Grid.SessionState',
  'K10MediaBroadcaster.Plugin.Grid.GriddedCars',
  'K10MediaBroadcaster.Plugin.Grid.TotalCars',
  'K10MediaBroadcaster.Plugin.Grid.PaceMode',
  'K10MediaBroadcaster.Plugin.Grid.StartType',
  'K10MediaBroadcaster.Plugin.Grid.LightsPhase',
  'K10MediaBroadcaster.Plugin.Demo.Grid.SessionState',
  'K10MediaBroadcaster.Plugin.Demo.Grid.GriddedCars',
  'K10MediaBroadcaster.Plugin.Demo.Grid.TotalCars',
  'K10MediaBroadcaster.Plugin.Demo.Grid.PaceMode',
  'K10MediaBroadcaster.Plugin.Demo.Grid.LightsPhase',
  'K10MediaBroadcaster.Plugin.Demo.Grid.StartType',
  'K10MediaBroadcaster.Plugin.Grid.TrackCountry',
  'K10MediaBroadcaster.Plugin.Demo.Grid.TrackCountry',
]

// Demo car models
export const DEMO_MODELS: Record<string, string> = {
  bmw: 'M4 GT3', mclaren: '720S GT3', mazda: 'MX-5 Cup', nissan: 'GTP ZX-T',
  dallara: 'IR-04', ferrari: '296 GT3', porsche: '911 GT3 R', audi: 'R8 LMS',
  mercedes: 'AMG GT3', lamborghini: 'Huracán GT3', chevrolet: 'Corvette Z06',
  ford: 'Mustang GT3', toyota: 'GR86', hyundai: 'Elantra N TC',
  cadillac: 'V-Series.R', astonmartin: 'Vantage GT3', lotus: 'Emira GT4',
  honda: 'Civic Type R', ligier: 'JS P320',
}

// Manufacturer branding
export const DEFAULT_LOGO_BG = 'hsla(0, 0%, 12%, 1.0)'

export const MFR_BRAND_COLORS: Record<string, string> = {
  bmw:         'hsla(204, 100%, 45%, 0.85)',
  mclaren:     'hsla(24, 100%, 52%, 0.85)',
  mazda:       'hsla(0, 90%, 44%, 0.85)',
  nissan:      'hsla(0, 85%, 50%, 0.85)',
  dallara:     'hsla(210, 85%, 48%, 0.85)',
  ferrari:     'hsla(0, 90%, 48%, 0.85)',
  porsche:     'hsla(0, 0%, 50%, 0.80)',
  audi:        'hsla(0, 0%, 50%, 0.80)',
  mercedes:    'hsla(175, 65%, 42%, 0.82)',
  lamborghini: 'hsla(48, 90%, 48%, 0.82)',
  chevrolet:   'hsla(40, 62%, 38%, 0.85)',
  ford:        'hsla(237, 100%, 28%, 0.85)',
  toyota:      'hsla(0, 85%, 48%, 0.85)',
  hyundai:     'hsla(216, 85%, 45%, 0.85)',
  cadillac:    'hsla(0, 0%, 50%, 0.80)',
  astonmartin: 'hsla(155, 70%, 38%, 0.85)',
  lotus:       'hsla(57, 100%, 50%, 0.85)',
  ligier:      'hsla(204, 78%, 40%, 0.85)',
}

export const MFR_MAP: Record<string, string> = {
  'bmw': 'bmw', 'm4 gt': 'bmw', 'm8 gte': 'bmw', 'm hybrid': 'bmw',
  'mclaren': 'mclaren', 'mp4': 'mclaren',
  'mazda': 'mazda', 'mx-5': 'mazda', 'miata': 'mazda',
  'nissan': 'nissan', 'gtp zx': 'nissan', 'nismo': 'nissan',
  'dallara': 'dallara', 'ir-01': 'dallara', 'ir01': 'dallara', 'ir-04': 'dallara', 'ir04': 'dallara',
  'ferrari': 'ferrari', '488': 'ferrari', '296': 'ferrari', 'sf-23': 'ferrari',
  'porsche': 'porsche', '911': 'porsche', 'cayman': 'porsche', 'boxter': 'porsche', '918': 'porsche',
  'audi': 'audi', 'r8': 'audi', 'rs e-tron gt': 'audi', 'e-tron gt': 'audi',
  'mercedes': 'mercedes', 'amg gt': 'mercedes', 'hypercar': 'mercedes',
  'lamborghini': 'lamborghini', 'huracán': 'lamborghini', 'huracan': 'lamborghini', 'urus': 'lamborghini',
  'chevrolet': 'chevrolet', 'corvette': 'chevrolet', 'chevy': 'chevrolet', 'c8': 'chevrolet',
  'ford': 'ford', 'mustang': 'ford', 'ford gt': 'ford', 'mk iv': 'ford',
  'toyota': 'toyota', 'gr86': 'toyota', 'gr corolla': 'toyota',
  'hyundai': 'hyundai', 'elantra': 'hyundai', 'ioniq': 'hyundai',
  'cadillac': 'cadillac', 'v-series': 'cadillac',
  'aston martin': 'astonmartin', 'vantage': 'astonmartin', 'dbs': 'astonmartin',
  'lotus': 'lotus', 'emira': 'lotus', 'evija': 'lotus',
  'honda': 'honda', 'civic': 'honda', 'nsx': 'honda',
  'ligier': 'ligier', 'js p3': 'ligier', 'js p320': 'ligier',
  'generic': 'generic', 'none': 'none',
}

export const CAR_NO_ADJUST: CarAdjustability[] = [
  { match: 'formula vee',      noBB: false, noABS: true, noTC: true },
  { match: 'skip barber',      noBB: false, noABS: true, noTC: true },
  { match: 'usf 2000',         noBB: false, noABS: true, noTC: true },
  { match: 'usf2000',          noBB: false, noABS: true, noTC: true },
  { match: 'indy pro 2000',    noBB: false, noABS: true, noTC: true },
  { match: 'formula 4',        noBB: false, noABS: true, noTC: true },
  { match: 'fia f4',           noBB: false, noABS: true, noTC: true },
  { match: 'ir-04',            noBB: false, noABS: true, noTC: true },
  { match: 'dallara f3',       noBB: false, noABS: true, noTC: true },
  { match: 'lotus 49',         noBB: true,  noABS: true, noTC: true },
  { match: 'lotus 79',         noBB: false, noABS: true, noTC: true },
  { match: 'mp4-30',           noBB: false, noABS: true, noTC: true },
  { match: 'w12',              noBB: false, noABS: true, noTC: true },
  { match: 'w13',              noBB: false, noABS: true, noTC: true },
  { match: 'js p320',          noBB: false, noABS: true, noTC: false },
  { match: 'ligier js',        noBB: false, noABS: true, noTC: false },
  { match: '992 cup',          noBB: false, noABS: true, noTC: true },
  { match: 'gt3 cup',          noBB: false, noABS: true, noTC: true },
  { match: 'supercars',        noBB: false, noABS: true, noTC: true },
  { match: 'supercar',         noBB: false, noABS: true, noTC: true },
  { match: 'ford falcon',      noBB: false, noABS: true, noTC: true },
  { match: 'holden commodore', noBB: false, noABS: true, noTC: true },
  { match: 'gen3 camaro',      noBB: false, noABS: true, noTC: true },
  { match: 'gen3 mustang',     noBB: false, noABS: true, noTC: true },
  { match: 'spec racer',       noBB: false, noABS: true, noTC: true },
  { match: 'legends',          noBB: true,  noABS: true, noTC: true },
  { match: '34 ford',          noBB: true,  noABS: true, noTC: true },
  { match: 'mx-5 cup',         noBB: false, noABS: true, noTC: true },
  { match: 'mx-5 roadster',    noBB: false, noABS: true, noTC: true },
  { match: 'gr86',             noBB: false, noABS: true, noTC: true },
  { match: 'solstice',         noBB: false, noABS: true, noTC: true },
  { match: 'nascar',           noBB: false, noABS: true, noTC: true },
  { match: 'gen 6',            noBB: false, noABS: true, noTC: true },
  { match: 'next gen',         noBB: false, noABS: true, noTC: true },
  { match: 'trucks',           noBB: false, noABS: true, noTC: true },
  { match: 'street stock',     noBB: true,  noABS: true, noTC: true },
  { match: 'late model',       noBB: false, noABS: true, noTC: true },
  { match: 'modified',         noBB: false, noABS: true, noTC: true },
  { match: 'silver crown',     noBB: false, noABS: true, noTC: true },
  { match: 'sprint car',       noBB: false, noABS: true, noTC: true },
  { match: 'midget',           noBB: false, noABS: true, noTC: true },
  { match: 'dirt',             noBB: false, noABS: true, noTC: true },
]

export const GAME_FEATURES: Record<string, GameFeatures> = {
  iracing:  { hasIRating: true,  hasIncidents: true,  hasFlags: true,  hasFormation: true,  hasDRS: true,  hasERS: true  },
  acc:      { hasIRating: false, hasIncidents: false, hasFlags: true,  hasFormation: true,  hasDRS: false, hasERS: true  },
  ac:       { hasIRating: false, hasIncidents: false, hasFlags: true,  hasFormation: false, hasDRS: false, hasERS: false },
  acevo:    { hasIRating: false, hasIncidents: false, hasFlags: true,  hasFormation: false, hasDRS: false, hasERS: false },
  acrally:  { hasIRating: false, hasIncidents: false, hasFlags: false, hasFormation: false, hasDRS: false, hasERS: false },
  lmu:      { hasIRating: false, hasIncidents: false, hasFlags: true,  hasFormation: true,  hasDRS: true,  hasERS: true  },
  raceroom: { hasIRating: false, hasIncidents: false, hasFlags: true,  hasFormation: true,  hasDRS: true,  hasERS: false },
  eawrc:    { hasIRating: false, hasIncidents: false, hasFlags: false, hasFormation: false, hasDRS: false, hasERS: false },
  forza:    { hasIRating: false, hasIncidents: false, hasFlags: false, hasFormation: false, hasDRS: false, hasERS: false },
}

export const DEFAULT_SETTINGS: Settings = {
  showFuel: true, showTyres: true, showControls: true, showPedals: true,
  showMaps: true, showPosition: true, showTacho: true, showCommentary: true,
  showK10Logo: true, showCarLogo: true,
  simhubUrl: 'http://localhost:8889/k10mediabroadcaster/',
  layoutPosition: 'top-right', layoutFlow: 'ltr', verticalSwap: false,
  greenScreen: false, showWebGL: true, showBonkers: true,
  zoom: 165, forceFlag: '',
  showLeaderboard: true, showDatastream: true, showIncidents: true, showSpotter: true,
  incPenalty: 17, incDQ: 25, secLayout: 'stack', secOffsetX: 0, secOffsetY: 0,
  secVOppose: true, secHOppose: true,
  discordUser: null,
  rallyMode: false,
}
