import { ReactNode } from 'react';
import { render, RenderOptions } from '@testing-library/react';

// Mock telemetry data matching ParsedTelemetry
export const mockTelemetry = {
  gameRunning: true,
  gear: '3',
  rpm: 6500,
  maxRpm: 8500,
  speedMph: 112,
  throttleRaw: 0.75,
  brakeRaw: 0.0,
  clutchRaw: 0.0,
  fuelLiters: 42.5,
  maxFuelLiters: 80,
  fuelPerLap: 3.2,
  fuelRemainingLaps: 13.3,
  tyreTempFL: 185,
  tyreTempFR: 190,
  tyreTempRL: 175,
  tyreTempRR: 180,
  tyreWearFL: 0.92,
  tyreWearFR: 0.89,
  tyreWearRL: 0.95,
  tyreWearRR: 0.93,
  brakeBias: 52.5,
  tc: 4,
  abs: 3,
  position: 5,
  gapAhead: 1.234,
  gapBehind: 0.867,
  driverAhead: 'M. Verstappen',
  driverBehind: 'L. Hamilton',
  irAhead: 5200,
  irBehind: 4800,
  currentLap: 12,
  totalLaps: 40,
  currentLapTime: 45.678,
  bestLapTime: 83.456,
  lastLapTime: 84.123,
  sessionBestLapTime: 82.900,
  sessionTime: 2400,
  remainingTime: 1200,
  iRating: 3500,
  safetyRating: 3.45,
  carModel: 'BMW M4 GT3',
  commentaryVisible: false,
  commentaryText: '',
  commentaryTitle: '',
  commentaryTopicId: '',
  commentaryCategory: '',
  commentaryColor: '',
  commentarySeverity: 0,
  latG: 0.5,
  longG: -0.3,
  yawRate: 0.12,
  steerTorque: 15.5,
  trackTemp: 32.5,
  incidentCount: 4,
  absActive: false,
  tcActive: false,
  trackPct: 0.45,
  lapDelta: -0.234,
  completedLaps: 11,
  isInPitLane: false,
  speedKmh: 180,
  trackMapReady: false,
  trackMapSvg: '',
  playerMapX: 50,
  playerMapY: 50,
  opponentMapPositions: '',
  leaderboardJson: '',
  driverFirstName: 'Kevin',
  driverLastName: 'Conboy',
  flagState: 'none',
  sessionState: '4',
  griddedCars: 0,
  totalCars: 0,
  paceMode: '',
  startType: 'rolling',
  lightsPhase: 0,
  trackCountry: 'US',
  demoMode: false,
  fuelPercent: 53.125,
};

// Mock settings matching OverlaySettings
export const mockSettings = {
  showFuel: true,
  showTyres: true,
  showControls: true,
  showPedals: true,
  showMaps: true,
  showPosition: true,
  showTacho: true,
  showCommentary: true,
  showK10Logo: true,
  showCarLogo: true,
  showLeaderboard: true,
  showDatastream: true,
  showIncidents: true,
  showWebGL: true,
  simhubUrl: 'http://localhost:8889/k10mediabroadcaster/',
  layoutPosition: 'top-right' as const,
  layoutFlow: 'rtl' as const,
  verticalSwap: false,
  greenScreen: false,
  zoom: 165,
  forceFlag: '',
  incPenalty: 17,
  incDQ: 25,
  secLayout: 'stack' as const,
  secOffsetX: 0,
  secOffsetY: 0,
};

export const mockStats = {
  pollCount: 100,
  connectedCount: 99,
  failureCount: 1,
  lastUpdateTime: Date.now(),
  averageLatencyMs: 15,
  connectionStatus: 'connected' as const,
};
